language: java
jdk:
- oraclejdk8
- openjdk8
- oraclejdk9

cache:
  apt: true
  directories:
  - $HOME/.m2

sudo: required

addons:
  apt:
    packages:
    - jq

matrix:
  allow_failures:
  - jdk: oraclejdk9
  fast_finish: true

script:
# run tests and integration tests
# see  https://stackoverflow.com/questions/34405047/how-do-you-merge-into-another-branch-using-travis-with-git-commands?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
- build_head=$(git rev-parse HEAD)
- git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
- git fetch origin $TRAVIS_BRANCH
- git checkout -f $TRAVIS_BRANCH
- git checkout $build_head
- git merge $TRAVIS_BRANCH
- VERSION=$(mvn git-commit-id:revision help:evaluate -Dexpression=project.version | grep -E '^[0-9.]+')
- VERSION=${VERSION/DEV*/RELEASE}
- echo $VERSION
- mvn versions:set -DnewVersion=$VERSION
# run jar sanity tests
- mvn integration-test -Dlogging-level=INFO
